### ISSUE TITLE
Squashed scaling of Upcoming Arts

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#1]
At some window widths the images for upcoming arts become squished. I would expect the images to remain at the correct aspect ratio, even if they need to shrink to accommodate and adjust the responsive layout. 

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/74c683b6-09cd-4ccb-a6f6-658f4d17bea9)

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/8848e536-1493-4344-bec4-7f35a933f095)

**Comment by SathishTeckas** [comment]
This issue is solved by altering this code.
[code](https://github.com/Teckas-Technologies/daily-art-battle/blob/19493ec43d84c579a5ee86e9253b211e5cf3002b/src/components/UpcomingBattlesTable.tsx#L71)

**Comment by starpause** [comment]
I'm still seeing squashed artwork on https://testnet-daily-art-battle.vercel.app/ is there a different site I should check? 

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/0dc579ed-2e2b-4c9f-87f9-de1afcbdac5b)
